version: "3.9"

services:
  mysql:
    image: mysql:5.7
    platform: ${ARCHITECTURE_PLATFORM}
    volumes:
      - ./wp_data:/var/lib/mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wordpress-network

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    env_file: .env
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./configuration/apache2.conf:/etc/apache2/apache2.conf:ro
    networks:
      - wordpress-network

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    ports:
      - ${WORDPRESS_PORT}:80
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-false}
    volumes:
      - ./wordpress:/var/www/html:rw
      - ./configuration/apache2.conf:/etc/apache2/apache2.conf:ro
    networks:
      - wordpress-network

  wp-cli:
    depends_on:
      - mysql
      - wordpress
    image: wordpress:cli
    env_file: .env
    # This is required to run wp-cli with the same
    # user-id as wordpress. This way there are no permission problems
    # when running the cli
    user: xfs
    environment:
      WP_CLI_CACHE_DIR: ${WP_CLI_CACHE_DIR}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./wordpress:/var/www/html:rw
      - ./bin/install-wp.sh:/usr/local/bin/install-wp:ro
    networks:
      - wordpress-network

volumes:
  db_data:
  wordpress:

networks:
  wordpress-network:
    driver: bridge
